# -*- coding: utf-8 -*-
{
    'name': 'Data Importer',
    'version': '1.0.0',
    'summary': 'Import CSV files into any Odoo model with special handling for users.',
    'description': 'Generic and reusable CSV importer supporting relational fields and dynamic templates.',
    'category': 'Tools',
    'author': 'Auto Generated by ChatGPT',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'subscription_management'],
    'data': [
        'security/ir.model.access.csv',
        'views/data_importer_views.xml',
    ],
    'assets': {},
    'application': True,
}
