"""Initialize models for zeeve_base."""
from . import protocol_master
from . import server_location
from . import contact_us
from . import zeeve_config
from . import res_users_reporting
from . import mail_mail
from . import mail_template
from . import mail_thread
from . import portal_wizard
from . import res_users
from . import res_partner
from . import ir_mail_server
from . import zeeve_notification
