{
    "name": "Rollup Management",
    "summary": "Manage rollup services, deployment lifecycle, and Stripe payments",
    "version": "1.0.0",
    "category": "Services/Blockchain",
    "author": "Zeeve",
    "website": "https://www.zeeve.net",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "account",
        "zeeve_base",
        "subscription_management",
    ],
    "data": [
        "security/rollup_security.xml",
        "security/ir.model.access.csv",
        "data/rollup_type_data.xml",
        "data/mail_templates.xml",
        "data/rollup_mail.xml",
        "data/rollup_mail_renewal.xml",
        "data/rollup_cron.xml",
        "report/rollup_invoice_report.xml",
        "views/rollup_service_views.xml",
        "views/account_move_views.xml",
        "views/rollup_type_views.xml",
        "views/rollup_data_availability_views.xml",
        "views/rollup_settlement_layer_views.xml",
        "views/rollup_node_views.xml",
        "views/rollup_sequencer_views.xml",
        "views/stripe_payment_log_views.xml",
        "views/menu_access.xml",
    ],
    "application": True,
    "installable": True,
}
